AWSTemplateFormatVersion: "2010-09-09"
Description: "Two-tier Architecture (VPC + Subnets + EC2 + ALB + RDS Ready) – HW2 + HW3 Style"

Parameters:
  KeyPairName:
    Description: EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  RegionMap:
    us-east-1:
      AMI: "ami-04b70fa74e45c3917"

Resources:

# ---------------- VPC ----------------
  ProjectVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

# ---------------- SUBNETS ----------------
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProjectVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: true

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProjectVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: us-east-1b
      MapPublicIpOnLaunch: true

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProjectVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: us-east-1a

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProjectVPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: us-east-1b

# ---------------- IGW + ROUTES ----------------
  IGW:
    Type: AWS::EC2::InternetGateway

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref ProjectVPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ProjectVPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  RouteAssocA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  RouteAssocB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable

# ---------------- SECURITY GROUPS ----------------
  AppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      VpcId: !Ref ProjectVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  DBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow DB from App Tier
      VpcId: !Ref ProjectVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref AppSG

# ---------------- ALB ----------------
  ProjectALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: project-alb
      Scheme: internet-facing
      Type: application
      Subnets:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
      SecurityGroups:
        - !Ref AppSG

  ProjectTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref ProjectVPC
      Port: 80
      Protocol: HTTP
      TargetType: instance

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ProjectALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ProjectTargetGroup

# ---------------- EC2 INSTANCES (t3.micro) ----------------
  WebServer1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyPairName
      ImageId: !FindInMap [RegionMap, us-east-1, AMI]
      SecurityGroupIds:
        - !Ref AppSG
      SubnetId: !Ref PublicSubnetA
      UserData: !Base64 |
        #!/bin/bash
        yum install -y httpd
        systemctl start httpd
        echo "WebServer1 is running" > /var/www/html/index.html

  WebServer2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyPairName
      ImageId: !FindInMap [RegionMap, us-east-1, AMI]
      SecurityGroupIds:
        - !Ref AppSG
      SubnetId: !Ref PublicSubnetB
      UserData: !Base64 |
        #!/bin/bash
        yum install -y httpd
        systemctl start httpd
        echo "WebServer2 is running" > /var/www/html/index.html

Outputs:
  LoadBalancerDNS:
    Description: DNS of the Application Load Balancer
    Value: !GetAtt ProjectALB.DNSName
